// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/date.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DateService_GetEndDate_FullMethodName              = "/date_service.DateService/GetEndDate"
	DateService_GetEndDateBidirectional_FullMethodName = "/date_service.DateService/GetEndDateBidirectional"
)

// DateServiceClient is the client API for DateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DateServiceClient interface {
	GetEndDate(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*DateResponse, error)
	GetEndDateBidirectional(ctx context.Context, opts ...grpc.CallOption) (DateService_GetEndDateBidirectionalClient, error)
}

type dateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDateServiceClient(cc grpc.ClientConnInterface) DateServiceClient {
	return &dateServiceClient{cc}
}

func (c *dateServiceClient) GetEndDate(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*DateResponse, error) {
	out := new(DateResponse)
	err := c.cc.Invoke(ctx, DateService_GetEndDate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dateServiceClient) GetEndDateBidirectional(ctx context.Context, opts ...grpc.CallOption) (DateService_GetEndDateBidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &DateService_ServiceDesc.Streams[0], DateService_GetEndDateBidirectional_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &dateServiceGetEndDateBidirectionalClient{stream}
	return x, nil
}

type DateService_GetEndDateBidirectionalClient interface {
	Send(*DateRequest) error
	Recv() (*DateResponse, error)
	grpc.ClientStream
}

type dateServiceGetEndDateBidirectionalClient struct {
	grpc.ClientStream
}

func (x *dateServiceGetEndDateBidirectionalClient) Send(m *DateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dateServiceGetEndDateBidirectionalClient) Recv() (*DateResponse, error) {
	m := new(DateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DateServiceServer is the server API for DateService service.
// All implementations must embed UnimplementedDateServiceServer
// for forward compatibility
type DateServiceServer interface {
	GetEndDate(context.Context, *DateRequest) (*DateResponse, error)
	GetEndDateBidirectional(DateService_GetEndDateBidirectionalServer) error
	mustEmbedUnimplementedDateServiceServer()
}

// UnimplementedDateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDateServiceServer struct {
}

func (UnimplementedDateServiceServer) GetEndDate(context.Context, *DateRequest) (*DateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndDate not implemented")
}
func (UnimplementedDateServiceServer) GetEndDateBidirectional(DateService_GetEndDateBidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEndDateBidirectional not implemented")
}
func (UnimplementedDateServiceServer) mustEmbedUnimplementedDateServiceServer() {}

// UnsafeDateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DateServiceServer will
// result in compilation errors.
type UnsafeDateServiceServer interface {
	mustEmbedUnimplementedDateServiceServer()
}

func RegisterDateServiceServer(s grpc.ServiceRegistrar, srv DateServiceServer) {
	s.RegisterService(&DateService_ServiceDesc, srv)
}

func _DateService_GetEndDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DateServiceServer).GetEndDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DateService_GetEndDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DateServiceServer).GetEndDate(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DateService_GetEndDateBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DateServiceServer).GetEndDateBidirectional(&dateServiceGetEndDateBidirectionalServer{stream})
}

type DateService_GetEndDateBidirectionalServer interface {
	Send(*DateResponse) error
	Recv() (*DateRequest, error)
	grpc.ServerStream
}

type dateServiceGetEndDateBidirectionalServer struct {
	grpc.ServerStream
}

func (x *dateServiceGetEndDateBidirectionalServer) Send(m *DateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dateServiceGetEndDateBidirectionalServer) Recv() (*DateRequest, error) {
	m := new(DateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DateService_ServiceDesc is the grpc.ServiceDesc for DateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "date_service.DateService",
	HandlerType: (*DateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEndDate",
			Handler:    _DateService_GetEndDate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEndDateBidirectional",
			Handler:       _DateService_GetEndDateBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/date.proto",
}
